### ISSUE TITLE
Specs-derive

### ISSUE THREAD

**Issue by jojolepro** [slide-rs/specs#452] opened 2018-08-13 19:54 UTC
Hi, 

In amethyst we want to re-export specs-derive, but it doesn't work with the way we re-export specs
(amethyst::ecs).

@omni-viral proposed this implementation to fix this issue: https://github.com/amethyst/amethyst/issues/551#issuecomment-405676793

**Comment by torkleyy** [comment] 2018-09-09 07:03
The problem is that with that solution you still need to add the crate to your `Cargo.toml`.

**Comment by jojolepro** [comment] 2018-09-09 14:13
May this be of some use? https://github.com/rust-lang/rust/pull/50911

**Comment by torkleyy** [comment] 2018-09-10 07:07
How would it solve our problem? Can you go into more detail, please?

**Comment by jojolepro** [comment] 2018-09-10 13:03
I'm not too sure, I was looking through the recent stabilizations to find things related to macro exports. I didn't really dig much into how it works and if it solves the issue.

**Comment by torkleyy** [comment] 2019-01-03 15:12
Issue addressed by https://github.com/slide-rs/shred/pull/103

**Closed by torkleyy** 2019-01-03 15:12 UTC
Labels: enhancement
